### ISSUE TITLE
Windows test

### ISSUE THREAD

**Issue by peroveh** [bulletmark/mpr#1]
Hi... Tool looks interesting.. and did some small tests on a windows 10 platform. It appears i have problems opening a serial port here. Tried various versions of COM4, 'COM4' and even renamed it to COM3 whereafter i checked -c3... But no dice.. Has this been tested on windows?

**Comment by bulletmark** [comment]
As per the README this is just a thin wrapper around [mpremote](https://docs.micropython.org/en/latest/reference/mpremote.html) so the obvious question is - does mpremote work on your platform?

I never use Windows and have never tested it there sorry.

**Comment by bulletmark** [comment]
No answer from OP so closing.
